const cards={
  cut:{name:'破浪斩',cost:1,type:'attack',art:'assets/cards/cut.webp',text:'造成 7 点伤害。',damage:7,weapon:'ram'},brace:{name:'压舷',cost:1,type:'skill',art:'assets/cards/brace.webp',text:'获得 6 点护甲。',block:6},
  flare:{name:'信号焰',cost:0,type:'attack',art:'assets/cards/flare.webp',text:'造成 3 点伤害。抽 1 张牌。',damage:3,draw:1,weapon:'flare'},broadside:{name:'舷侧齐射',cost:2,type:'attack',art:'assets/cards/broadside.webp',text:'造成 15 点伤害。',damage:15,weapon:'broadside'},
  tidewall:{name:'潮汐壁垒',cost:2,type:'skill',art:'assets/cards/tidewall.webp',text:'获得 14 点护甲。',block:14},mark:{name:'标定航线',cost:1,type:'skill',art:'assets/cards/mark.webp',text:'获得 4 点护甲。抽 2 张牌。',block:4,draw:2},
  undertow:{name:'暗流',cost:1,type:'attack',art:'assets/cards/undertow.webp',text:'造成 5 点伤害。施加 2 层锈蚀。',damage:5,vulnerable:2,weapon:'torpedo'},salvage:{name:'沉船打捞',cost:1,type:'skill',art:'assets/cards/salvage.webp',text:'获得 8 点护甲。恢复 2 点生命。',block:8,heal:2},
  storm:{name:'风暴眼',cost:3,type:'attack',art:'assets/cards/storm.webp',text:'造成 24 点伤害。',damage:24,weapon:'lightning'},current:{name:'顺流',cost:0,type:'skill',art:'assets/cards/current.webp',text:'获得 1 点潮力。抽 1 张牌。',energy:1,draw:1},
  harpoon:{name:'回收鱼叉',cost:1,type:'attack',art:'assets/cards/harpoon.webp',text:'造成 9 点伤害。',damage:9,weapon:'harpoon'},calm:{name:'静水时刻',cost:1,type:'skill',art:'assets/cards/calm.webp',text:'获得 5 点护甲。恢复 3 点生命。',block:5,heal:3}
};
const hardware={
  reinforcedHull:{name:'铆接装甲带',icon:'▰',text:'最大生命 +12，并立刻修复 12 点。'},
  powderMagazine:{name:'红铜火药舱',icon:'✹',text:'所有攻击额外造成 2 点伤害。'},
  tideCapacitor:{name:'潮汐蓄能轮',icon:'◉',text:'每场战斗的第一回合获得 1 点额外潮力。'},
  foamProjector:{name:'泡沫隔舱器',icon:'⬡',text:'每场战斗开始时获得 6 点护甲。'},
  deckWinch:{name:'高速甲板绞盘',icon:'⌁',text:'每场战斗的第一回合额外抽 1 张牌。'},
  repairDrone:{name:'黄铜维修艇',icon:'✦',text:'每场战斗后额外修复 5 点生命。'}
};
const xpThresholds=[0,50,110,190,290,410];
const encounters=[
  [
    {name:'盐蚀掠夺者',title:'从雾里包抄',sprite:'raider',variant:0,hp:27,moves:[{kind:'attack',value:6},{kind:'blockAttack',value:4,block:4},{kind:'attack',value:8}]},
    {name:'焦油鸥',title:'啄食落单的水手',sprite:'raider',variant:1,hp:21,moves:[{kind:'attack',value:5},{kind:'attack',value:7},{kind:'block',block:6}]}
  ],
  [
    {name:'横风走私船',title:'借着侧风突然切入',sprite:'raider',variant:4,hp:34,moves:[{kind:'attack',value:7},{kind:'block',block:7},{kind:'attack',value:10}]},
    {name:'漂雷艇',title:'把爆裂物藏在浪尖',sprite:'raider',variant:5,hp:25,moves:[{kind:'blockAttack',value:5,block:4},{kind:'attack',value:9},{kind:'attack',value:6}]}
  ],
  [
    {name:'铆钉潜兽',title:'以沉船的铁骨为食',sprite:'raider',variant:2,hp:44,moves:[{kind:'attack',value:9},{kind:'block',block:10},{kind:'attack',value:13}]},
    {name:'深沟拖网者',title:'把猎物拖入暗流',sprite:'raider',variant:3,hp:32,moves:[{kind:'blockAttack',value:6,block:5},{kind:'attack',value:10},{kind:'attack',value:7}]}
  ],
  [
    {name:'珊瑚装甲舰',title:'船壳长满锋利的旧礁',sprite:'raider',variant:6,hp:55,moves:[{kind:'block',block:12},{kind:'attack',value:14},{kind:'blockAttack',value:8,block:6}]},
    {name:'雾哨快艇',title:'替重舰寻找射击角度',sprite:'raider',variant:7,hp:29,moves:[{kind:'attack',value:7},{kind:'attack',value:9},{kind:'block',block:5}]}
  ],
  [
    {name:'雷云捕手',title:'桅杆上缠着活的闪电',sprite:'raider',variant:8,hp:43,moves:[{kind:'attack',value:10},{kind:'blockAttack',value:7,block:6},{kind:'attack',value:12}]},
    {name:'裂帆追猎者',title:'只追逐受伤的船',sprite:'raider',variant:9,hp:39,moves:[{kind:'attack',value:8},{kind:'attack',value:11},{kind:'block',block:8}]},
    {name:'浪底投弹艇',title:'贴着黑浪投放火药',sprite:'raider',variant:10,hp:24,moves:[{kind:'block',block:5},{kind:'attack',value:8},{kind:'attack',value:6}]}
  ],
  [{name:'无灯领航者',title:'它知道每一条错误的航线',sprite:'boss',variant:0,hp:116,moves:[{kind:'attack',value:14},{kind:'blockAttack',value:10,block:10},{kind:'attack',value:20},{kind:'block',block:16}]}]
];
let state,selected=null,overlayClose=()=>{};
const $=s=>document.querySelector(s);
const audio=createGameAudio();
function loadProfile(){try{return JSON.parse(localStorage.getItem('wakebound-profile-v1'))||{xp:0}}catch{return{xp:0}}}
function saveProfile(){try{localStorage.setItem('wakebound-profile-v1',JSON.stringify(state.profile))}catch{}}
function levelForXp(xp){let level=1;while(level<xpThresholds.length&&xp>=xpThresholds[level])level++;return level}
function xpProgress(){const level=levelForXp(state.profile.xp),start=xpThresholds[level-1]||0,end=xpThresholds[level]||start+150;return`${state.profile.xp-start} / ${end-start}`}
function parseCard(ref){return{base:ref.replace(/\+$/,''),upgraded:ref.endsWith('+')}}
function getCard(ref){const {base,upgraded}=parseCard(ref),original=cards[base];if(!upgraded)return original;const card={...original,name:`${original.name}+`};if(card.damage)card.damage+=3;if(card.block)card.block+=3;if(card.heal)card.heal+=1;const parts=[];if(card.damage)parts.push(`造成 ${card.damage} 点伤害。`);if(card.block)parts.push(`获得 ${card.block} 点护甲。`);if(card.heal)parts.push(`恢复 ${card.heal} 点生命。`);if(card.vulnerable)parts.push(`施加 ${card.vulnerable} 层锈蚀。`);if(card.energy)parts.push(`获得 ${card.energy} 点潮力。`);if(card.draw)parts.push(`抽 ${card.draw} 张牌。`);card.text=parts.join('');return card}
function hasHardware(id){return state.hardware.includes(id)}
function createGameAudio(){
  const tracks={map:'assets/audio/map-fog-sea.mp3',battle:'assets/audio/battle-black-sails.mp3',boss:'assets/audio/boss-storm-pursuit.mp3'};
  let context=null,master=null,currentTrack=null,currentScene='map',started=false,muted=false;
  function ensure(){if(context)return context;const AudioContext=globalThis.AudioContext||globalThis.webkitAudioContext;if(!AudioContext)return null;context=new AudioContext();master=context.createGain();master.gain.value=.42;master.connect(context.destination);return context}
  function tone(from,to,duration,type='triangle',volume=.16,delay=0){const ctx=ensure();if(!ctx||muted)return;const now=ctx.currentTime+delay,osc=ctx.createOscillator(),gain=ctx.createGain();osc.type=type;osc.frequency.setValueAtTime(from,now);osc.frequency.exponentialRampToValueAtTime(Math.max(20,to),now+duration);gain.gain.setValueAtTime(.001,now);gain.gain.exponentialRampToValueAtTime(volume,now+.015);gain.gain.exponentialRampToValueAtTime(.001,now+duration);osc.connect(gain).connect(master);osc.start(now);osc.stop(now+duration+.03)}
  function noise(duration=.25,volume=.16,frequency=900){const ctx=ensure();if(!ctx||muted)return;const length=Math.floor(ctx.sampleRate*duration),buffer=ctx.createBuffer(1,length,ctx.sampleRate),data=buffer.getChannelData(0);for(let i=0;i<length;i++)data[i]=(Math.random()*2-1)*(1-i/length);const source=ctx.createBufferSource(),filter=ctx.createBiquadFilter(),gain=ctx.createGain();source.buffer=buffer;filter.type='lowpass';filter.frequency.value=frequency;gain.gain.value=volume;source.connect(filter).connect(gain).connect(master);source.start()}
  function play(name){if(!started||muted)return;ensure()?.resume();if(name==='select'){tone(310,520,.12,'triangle',.1);tone(620,430,.1,'sine',.06,.07)}else if(name==='cannon'){tone(82,38,.38,'sawtooth',.28);noise(.3,.32,520)}else if(name==='torpedo'){tone(145,48,.52,'sine',.2);noise(.42,.1,260)}else if(name==='harpoon'){tone(780,220,.24,'square',.1);noise(.15,.12,1500)}else if(name==='lightning'){noise(.48,.34,2100);tone(180,48,.42,'sawtooth',.25)}else if(name==='ram'){noise(.38,.2,700);tone(120,62,.3,'triangle',.18)}else if(name==='flare'){tone(420,980,.35,'sine',.13);noise(.18,.08,1800)}else if(name==='hit'){tone(120,54,.22,'square',.16);noise(.18,.2,1200)}else if(name==='shield'){tone(180,760,.48,'sine',.16);tone(260,920,.54,'triangle',.08,.05)}else if(name==='turn'){tone(420,380,.45,'sine',.11);tone(630,560,.4,'sine',.08,.12)}else if(name==='reward'){[440,554,659].forEach((f,i)=>tone(f,f*1.01,.35,'triangle',.09,i*.1))}else if(name==='victory'){[392,494,587,784].forEach((f,i)=>tone(f,f*1.02,.55,'triangle',.12,i*.14))}else if(name==='defeat'){[220,174,130].forEach((f,i)=>tone(f,f*.72,.6,'sawtooth',.1,i*.18))}else if(name==='sail'){noise(.5,.07,340);tone(260,210,.45,'sine',.07)}}
  function setScene(scene){currentScene=scene;if(!started||muted)return;if(currentTrack?.dataset.scene===scene&&!currentTrack.paused)return;currentTrack?.pause();const music=new Audio(tracks[scene]);music.dataset.scene=scene;music.loop=true;music.volume=scene==='map'?.3:.26;currentTrack=music;music.play().catch(()=>{})}
  function start(){started=true;ensure()?.resume();setScene(currentScene);play('sail');updateButton()}
  function toggle(){muted=!muted;if(muted)currentTrack?.pause();else setScene(currentScene);if(master)master.gain.value=muted?0:.42;updateButton();return muted}
  function updateButton(){const button=$('#audio-toggle');if(!button)return;button.textContent=muted?'声音 关':'声音 开';button.setAttribute('aria-pressed',String(muted))}
  function stop(){currentTrack?.pause();context?.close();context=null}
  return{start,toggle,play,setScene,stop}
}
function newRun(){const profile=loadProfile(),level=levelForXp(profile.xp),maxHp=72+(level-1)*4;state={profile,floor:0,gold:90+(level-1)*15,hero:{hp:maxHp,max:maxHp,block:0},hardware:[],enemies:[],deck:['cut','cut','cut','cut','brace','brace','brace','brace','flare','broadside'],draw:[],discard:[],hand:[],energy:3,turn:1,locked:false,battleRewarded:false};$('#overlay').classList.add('hidden');showMap();$('#welcome').classList.remove('hidden')}
function showMap(){cancelTarget();audio.setScene('map');$('#battle-scene').classList.add('hidden');$('#map-scene').classList.remove('hidden');renderHud();renderMap()}
function enterNode(){if(Number(this.dataset.floor)===state.floor){audio.play('sail');startBattle()}}
function startBattle(){audio.setScene(state.floor===encounters.length-1?'boss':'battle');state.enemies=encounters[state.floor].map(e=>({...e,hp:e.hp,max:e.hp,block:0,move:0,vulnerable:0,sinkShown:false}));state.draw=shuffle([...state.deck]);state.discard=[];state.hand=[];state.turn=1;state.energy=3+(hasHardware('tideCapacitor')?1:0);state.hero.block=hasHardware('foamProjector')?6:0;state.locked=false;state.battleRewarded=false;draw(5+(hasHardware('deckWinch')?1:0));$('#map-scene').classList.add('hidden');$('#battle-scene').classList.remove('hidden');render();if(state.hero.block)showShield($('.hero'));announce('你的回合')}
function shuffle(a){for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function draw(n){for(let i=0;i<n;i++){if(!state.draw.length){if(!state.discard.length)return;state.draw=shuffle(state.discard);state.discard=[]}if(state.hand.length<8)state.hand.push(state.draw.pop())}}
function play(index,targetIndex=null){
  if(state.locked)return;const id=state.hand[index],c=getCard(id);if(!c||c.cost>state.energy)return announce('潮力不足');
  if(c.type==='attack'){const target=state.enemies[targetIndex];if(!target||target.hp<=0)return;audio.play(c.weapon||'cannon');const enemyEl=document.querySelector(`.enemy-target[data-index="${targetIndex}"]`);animateAttack($('.hero'),enemyEl,'hero',c.weapon||'cannon');let amount=c.damage+(hasHardware('powderMagazine')?2:0);if(target.vulnerable>0)amount=Math.ceil(amount*1.5);deal(target,amount,enemyEl?.querySelector('.portrait'));if(c.vulnerable)target.vulnerable+=c.vulnerable}
  state.energy-=c.cost;if(c.block){audio.play('shield');state.hero.block+=c.block;showShield($('.hero'))}else if(c.type==='skill')audio.play('select');if(c.heal)state.hero.hp=Math.min(state.hero.max,state.hero.hp+c.heal);if(c.energy)state.energy+=c.energy;state.hand.splice(index,1);state.discard.push(id);if(c.draw)draw(c.draw);cancelTarget();render();if(state.enemies.every(e=>e.hp<=0))winBattle()
}
function deal(target,amount,element){const absorbed=Math.min(target.block,amount),taken=amount-absorbed;target.block-=absorbed;target.hp=Math.max(0,target.hp-taken);if(taken)audio.play('hit');if(element){const unit=element.closest('.combatant')||element;unit.classList.remove('damage-flash');void unit.offsetWidth;unit.classList.add('damage-flash');spawnNumber(element,taken?`-${taken}`:'格挡',taken>0);spawnSparks(element,taken>0)}}
function spawnNumber(el,text,hurt){const r=el.getBoundingClientRect(),n=document.createElement('div');n.className=`float-number ${hurt?'hurt':'blocked'}`;n.textContent=text;n.style.left=`${r.left+r.width/2}px`;n.style.top=`${r.top+r.height/3}px`;document.body.appendChild(n);setTimeout(()=>n.remove(),850)}
function spawnSparks(el,hurt){if(!hurt)return;const r=el.getBoundingClientRect();for(let i=0;i<7;i++){const s=document.createElement('i');s.className='hit-spark';s.style.left=`${r.left+r.width/2}px`;s.style.top=`${r.top+r.height/2}px`;s.style.setProperty('--sx',`${(Math.random()-.5)*100}px`);s.style.setProperty('--sy',`${-20-Math.random()*70}px`);document.body.appendChild(s);setTimeout(()=>s.remove(),620)}}
function showShield(unit){if(!unit)return;const r=unit.getBoundingClientRect(),s=document.createElement('div');s.className='shield-burst';s.style.left=`${r.left+r.width/2}px`;s.style.top=`${r.top+r.height/2}px`;document.body.appendChild(s);unit.classList.add('bracing');setTimeout(()=>unit.classList.remove('bracing'),500);setTimeout(()=>s.remove(),720)}
function animateAttack(source,target,side,weapon='cannon'){
  if(!source||!target)return;source.classList.add('ship-attacking');const a=source.querySelector('.portrait').getBoundingClientRect(),b=target.querySelector('.portrait').getBoundingClientRect(),startX=a.left+a.width/2,startY=a.top+a.height*.58,endX=b.left+b.width/2,endY=b.top+b.height*.55;
  const launch=(className,delay=0,offset=0)=>{const shot=document.createElement('div');shot.className=`${className} ${side}`;shot.style.left=`${startX}px`;shot.style.top=`${startY+offset}px`;shot.style.setProperty('--dx',`${endX-startX}px`);shot.style.setProperty('--dy',`${endY-startY-offset}px`);shot.style.animationDelay=`${delay}ms`;document.body.appendChild(shot);setTimeout(()=>shot.remove(),760+delay)};
  if(weapon==='lightning'){const bolt=document.createElement('div');bolt.className='lightning-strike';bolt.style.left=`${endX}px`;bolt.style.top=`${Math.max(58,b.top-160)}px`;bolt.style.height=`${Math.min(250,b.top+80)}px`;document.body.appendChild(bolt);setTimeout(()=>bolt.remove(),620)}
  else if(weapon==='broadside'){[-10,0,10].forEach((offset,i)=>launch('cannon-shot broadside-shot',i*75,offset))}
  else if(weapon==='torpedo')launch('torpedo-shot');
  else if(weapon==='harpoon')launch('harpoon-shot');
  else if(weapon==='flare')launch('flare-shot');
  else if(weapon==='ram')launch('ram-wave');
  else launch('cannon-shot');
  setTimeout(()=>source.classList.remove('ship-attacking'),420)
}
function endTurn(){if(state.locked)return;audio.play('turn');cancelTarget();state.locked=true;state.discard.push(...state.hand);state.hand=[];render();announce('敌方回合');setTimeout(()=>runEnemyTurn(0),650)}
function runEnemyTurn(index){while(index<state.enemies.length&&state.enemies[index].hp<=0)index++;if(index>=state.enemies.length)return setTimeout(beginTurn,550);const enemy=state.enemies[index],m=enemy.moves[enemy.move%enemy.moves.length],enemyEl=document.querySelector(`.enemy-target[data-index="${index}"]`);enemy.block=0;if(m.block){audio.play('shield');enemy.block+=m.block;showShield(enemyEl)}if(m.value){audio.play('cannon');animateAttack(enemyEl,$('.hero'),'enemy');setTimeout(()=>{deal(state.hero,m.value,$('#hero-portrait'));finishEnemyAction(enemy,index)},230)}else finishEnemyAction(enemy,index)}
function finishEnemyAction(enemy,index){enemy.move++;if(enemy.vulnerable>0)enemy.vulnerable--;render();if(state.hero.hp<=0)return gameOver();setTimeout(()=>runEnemyTurn(index+1),520)}
function beginTurn(){state.hero.block=0;state.energy=3;state.turn++;state.locked=false;draw(5);render();announce('你的回合')}
function intentText(enemy){const m=enemy.moves[enemy.move%enemy.moves.length];if(m.kind==='block')return `防御 ${m.block}`;if(m.kind==='blockAttack')return `攻击 ${m.value} · 护甲 ${m.block}`;return `攻击 ${m.value}`}
function announce(text){const b=$('#turn-banner');b.firstChild.textContent=text;b.querySelector('small').textContent=`第 ${state.turn} 回合`;b.classList.remove('show');void b.offsetWidth;b.classList.add('show')}
function selectTargetCard(index,card,event,targetType){event.stopPropagation();if(state.locked||getCard(state.hand[index]).cost>state.energy)return announce('潮力不足');if(selected?.index===index)return cancelTarget();audio.play('select');cancelTarget();selected={index,card,targetType,x:event.clientX,y:event.clientY};card.classList.add('selected');const targeting=$('#targeting');targeting.classList.remove('hidden');targeting.classList.toggle('defense',targetType==='hero');if(targetType==='enemy')document.querySelectorAll('.enemy-target:not(.defeated)').forEach(e=>e.classList.add('target-ready'));else $('.hero').classList.add('self-target-ready');window.addEventListener('pointermove',moveTarget);moveTarget(event);$('#hint').textContent=targetType==='enemy'?'移动箭头并点击一名敌人 · Esc 取消':'移动箭头并点击自己的船 · Esc 取消'}
function selectAttack(index,card,event){selectTargetCard(index,card,event,'enemy')}
function selectDefense(index,card,event){selectTargetCard(index,card,event,'hero')}
function moveTarget(event){if(!selected)return;selected.x=event.clientX;selected.y=event.clientY;const r=selected.card.getBoundingClientRect(),sx=r.left+r.width/2,sy=r.top+8,ex=event.clientX,ey=event.clientY,curve=Math.max(55,Math.abs(ex-sx)*.25);$('#target-path').setAttribute('d',`M ${sx} ${sy} C ${sx} ${sy-curve}, ${ex} ${ey+curve}, ${ex} ${ey}`);if(selected.targetType==='enemy')document.querySelectorAll('.enemy-target:not(.defeated)').forEach(enemy=>{const er=enemy.getBoundingClientRect();enemy.classList.toggle('target-hover',ex>=er.left&&ex<=er.right&&ey>=er.top&&ey<=er.bottom)});else{const hero=$('.hero'),hr=hero.getBoundingClientRect();hero.classList.toggle('self-target-hover',ex>=hr.left&&ex<=hr.right&&ey>=hr.top&&ey<=hr.bottom)}}
function chooseTarget(index,event){event.stopPropagation();if(!selected||selected.targetType!=='enemy'||state.enemies[index].hp<=0)return;play(selected.index,index)}
function chooseSelf(event){event.stopPropagation();if(!selected||selected.targetType!=='hero')return;play(selected.index)}
function cancelTarget(){window.removeEventListener('pointermove',moveTarget);selected?.card?.classList.remove('selected');selected=null;$('#targeting').classList.add('hidden');$('#targeting').classList.remove('defense');document.querySelectorAll('.enemy-target').forEach(e=>e.classList.remove('target-ready','target-hover'));$('.hero')?.classList.remove('self-target-ready','self-target-hover');const hint=$('#hint');if(hint)hint.textContent='攻击牌点敌船 · 防御牌点自己的船'}
function winBattle(){if(state.battleRewarded)return;state.battleRewarded=true;state.locked=true;const xp=awardXp([25,30,40,45,55,100][state.floor]||25);render();setTimeout(()=>state.floor===encounters.length-1?victory(xp):showRewards(xp),650)}
function awardXp(amount){const before=levelForXp(state.profile.xp);state.profile.xp+=amount;const after=levelForXp(state.profile.xp),levels=after-before;if(levels>0){state.hero.max+=levels*4;state.hero.hp=Math.min(state.hero.max,state.hero.hp+levels*4)}saveProfile();return{amount,leveled:levels>0,level:after}}
function showRewards(xp){
  audio.play('reward');const cardId=shuffle(Object.keys(cards).filter(x=>!['cut','brace'].includes(x)))[0],gold=[55,60,85,75,90][state.floor]||55,available=Object.keys(hardware).filter(id=>!hasHardware(id)),hardwareId=shuffle(available)[0]||'reinforcedHull';
  $('#modal-eyebrow').textContent=`第 ${state.floor+1} 场战斗 · 获得 ${xp.amount} 经验${xp.leveled?` · 升至 ${xp.level} 级`:''}`;$('#modal-title').textContent='只带走一件战利品';$('#modal-copy').textContent='卡牌扩充战术，金币用于船坞整备，硬件会永久强化本次航行。';const rewards=$('#rewards');rewards.className='rewards mixed-rewards';rewards.innerHTML='';rewards.appendChild(rewardChoice('tactic','',getCard(cardId).name,getCard(cardId).text,'战术卡牌',()=>takeReward(cardId),getCard(cardId).art));rewards.appendChild(rewardChoice('currency','◈',`${gold} 枚金币`,'用于强化或拆解卡牌。','航海物资',()=>takeGold(gold)));rewards.appendChild(rewardChoice('hardware',hardware[hardwareId].icon,hardware[hardwareId].name,hardware[hardwareId].text,'船体硬件',()=>takeHardware(hardwareId)));$('#skip-reward').textContent='放弃战利品';$('#skip-reward').classList.remove('hidden');overlayClose=returnToMap;$('#overlay').classList.remove('hidden')
}
function rewardChoice(type,icon,title,copy,label,onClick,art=''){const button=document.createElement('button');button.className=`reward-choice reward-${type}`;button.innerHTML=`<span class="reward-label">${label}</span><span class="reward-visual">${art?`<img src="${art}" alt="">`:`<b>${icon}</b>`}</span><span class="reward-copy"><strong>${title}</strong><small>${copy}</small></span><span class="reward-select">带走这件</span>`;button.onclick=onClick;return button}
function takeReward(id){state.deck.push(id);returnToMap()}
function takeGold(amount){state.gold+=amount;returnToMap()}
function takeHardware(id){if(!hasHardware(id))state.hardware.push(id);if(id==='reinforcedHull'){state.hero.max+=12;state.hero.hp=Math.min(state.hero.max,state.hero.hp+12)}returnToMap()}
function returnToMap(){state.floor++;state.hero.hp=Math.min(state.hero.max,state.hero.hp+12+(hasHardware('repairDrone')?5:0));$('#overlay').classList.add('hidden');showMap()}
function closeDrydock(){$('#overlay').classList.add('hidden');renderHud()}
function openDrydock(){audio.play('select');const list=state.hardware.length?state.hardware.map(id=>hardware[id].name).join(' · '):'尚未安装硬件';$('#modal-eyebrow').textContent='航线船坞';$('#modal-title').textContent='整备甲板';$('#modal-copy').textContent=`持有 ${state.gold} 金币 · ${list}`;const rewards=$('#rewards');rewards.className='rewards dock-actions';rewards.innerHTML='<button class="dock-action" data-mode="upgrade"><b>⬆</b><strong>强化卡牌</strong><span>75 金币 · 提升伤害、护甲或修复量</span></button><button class="dock-action danger" data-mode="remove"><b>✂</b><strong>拆解卡牌</strong><span>55 金币 · 精简牌组，提高抽牌稳定性</span></button>';rewards.querySelectorAll('.dock-action').forEach(button=>button.onclick=()=>showDeckOperation(button.dataset.mode));$('#skip-reward').textContent='返回航线';$('#skip-reward').classList.remove('hidden');overlayClose=closeDrydock;$('#overlay').classList.remove('hidden')}
function showDeckOperation(mode){const upgrade=mode==='upgrade',cost=upgrade?75:55;$('#modal-title').textContent=upgrade?'选择要强化的卡牌':'选择要拆解的卡牌';$('#modal-copy').textContent=`本次需要 ${cost} 金币。${upgrade?'已强化的卡牌不能再次强化。':'牌组至少保留 6 张牌。'}`;const rewards=$('#rewards');rewards.className='rewards deck-picker';rewards.innerHTML='';state.deck.forEach((ref,index)=>{const card=cardElement(ref,null,true,()=>operateDeck(mode,index));if(upgrade&&parseCard(ref).upgraded){card.disabled=true;card.classList.add('unplayable')}rewards.appendChild(card)});$('#skip-reward').textContent='返回整备';overlayClose=openDrydock}
function operateDeck(mode,index){const cost=mode==='upgrade'?75:55;if(state.gold<cost){$('#modal-copy').textContent=`金币不足：需要 ${cost}，当前只有 ${state.gold}。`;audio.play('defeat');return}if(mode==='remove'&&state.deck.length<=6){$('#modal-copy').textContent='牌组至少要保留 6 张牌，不能继续拆解。';return}if(mode==='upgrade'){const parsed=parseCard(state.deck[index]);if(parsed.upgraded)return;state.deck[index]=`${parsed.base}+`}else state.deck.splice(index,1);state.gold-=cost;audio.play('reward');renderHud();openDrydock()}
function gameOver(){audio.play('defeat');showEnd('航线中断','你的船沉入了无光海。下一次航行会保留你的经验。','再次启航')}
function victory(xp){audio.play('victory');showEnd('你穿过了风暴',`塔心的灯重新亮起。本场获得 ${xp.amount} 经验，船长等级 ${levelForXp(state.profile.xp)}。`,'开始新航程')}
function showEnd(title,copy,button){$('#modal-eyebrow').textContent='航程记录';$('#modal-title').textContent=title;$('#modal-copy').textContent=copy;$('#rewards').className='rewards';$('#rewards').innerHTML=`<button class="primary-button" id="again">${button}</button>`;$('#skip-reward').classList.add('hidden');$('#overlay').classList.remove('hidden');$('#again').onclick=newRun}
function cardElement(id,index,reward=false,onSelect=null){const c=getCard(id),upgraded=parseCard(id).upgraded,b=document.createElement('button');b.className=`card ${c.type}${upgraded?' upgraded':''}${!reward&&c.cost>state.energy?' unplayable':''}`;b.innerHTML=`<span class="card-cost">${c.cost}</span>${upgraded?'<span class="upgrade-mark">+</span>':''}<div class="card-art"><img src="${c.art}" alt=""></div><h3>${c.name}</h3><p>${c.text}</p><span class="card-type">${c.type==='attack'?'攻击':'技能'}</span>`;if(onSelect)b.onclick=onSelect;else if(reward)b.onclick=()=>takeReward(id);else if(c.type==='attack')b.onclick=e=>selectAttack(index,b,e);else if(c.block)b.onclick=e=>selectDefense(index,b,e);else b.onclick=e=>{e.stopPropagation();play(index)};return b}
function enemyElement(enemy,index){const el=document.createElement('article'),src=enemy.sprite==='boss'?'assets/boss-ship-v1.png':'assets/raider-ship-v1.png',defeatClass=enemy.hp<=0?(enemy.sinkShown?' defeated sunk':' defeated sinking'):'';el.className=`combatant enemy enemy-target ship-${enemy.sprite}${enemy.block?' has-block':''}${defeatClass}`;el.dataset.index=index;el.style.setProperty('--variant',enemy.variant||0);el.innerHTML=`<div class="intent"><small>下一步</small><strong>${enemy.hp>0?intentText(enemy):'已击败'}</strong></div><div class="portrait enemy-portrait"><img class="ship-sprite" src="${src}" alt="${enemy.name}"></div><div class="nameplate"><strong>${enemy.name}</strong><small>${enemy.title}</small></div><div class="health"><div style="width:${enemy.hp/enemy.max*100}%"></div><span>${enemy.hp} / ${enemy.max}</span></div><div class="status-row"><span class="status ${enemy.block?'':'hidden'}">护甲 ${enemy.block}</span><span>${enemy.vulnerable?`锈蚀 ${enemy.vulnerable}`:''}</span></div>`;el.onclick=e=>chooseTarget(index,e);return el}
function renderHud(){const level=levelForXp(state.profile.xp);$('#hud-hp').textContent=`${state.hero.hp} / ${state.hero.max}`;$('#hud-gold').textContent=state.gold;$('#hud-level').textContent=level;$('#hud-xp').textContent=xpProgress();$('#floor').textContent=`${Math.min(state.floor+1,encounters.length)} / ${encounters.length}`;$('#deck-count').textContent=state.deck.length;$('#hardware-count').textContent=state.hardware.length}
function renderMap(){const positions=[[10,78],[26,57],[42,70],[58,45],[73,54],[88,20]],pos=positions[Math.min(state.floor,positions.length-1)];document.querySelectorAll('.chart-node').forEach((node,i)=>{node.classList.toggle('cleared',i<state.floor);node.classList.toggle('current',i===state.floor);node.classList.toggle('locked',i>state.floor);node.disabled=i!==state.floor});$('#map-ship-token').style.setProperty('--ship-x',`${pos[0]}%`);$('#map-ship-token').style.setProperty('--ship-y',`${pos[1]}%`);$('#map-guidance').textContent=state.floor===encounters.length-1?'风暴中心就在前方。准备迎战首领。':'点击发光节点进入战斗，或先在船坞整备牌组'}
function render(){renderHud();const h=state.hero;$('.hero').classList.toggle('has-block',h.block>0);$('#hero-health').textContent=`${h.hp} / ${h.max}`;$('#hero-health-bar').style.width=`${h.hp/h.max*100}%`;$('#hero-block').textContent=`护甲 ${h.block}`;$('#hero-block').classList.toggle('hidden',!h.block);$('#energy').textContent=state.energy;$('#draw-count').textContent=state.draw.length;$('#discard-count').textContent=state.discard.length;const enemies=$('#enemies');enemies.className=`enemies enemies-${state.enemies.length}`;enemies.innerHTML='';state.enemies.forEach((enemy,i)=>{const wasNewSink=enemy.hp<=0&&!enemy.sinkShown;enemies.appendChild(enemyElement(enemy,i));if(wasNewSink)enemy.sinkShown=true});$('#hand').innerHTML='';const mid=(state.hand.length-1)/2;state.hand.forEach((id,i)=>{const card=cardElement(id,i),offset=i-mid;card.style.setProperty('--rot',`${offset*3.5}deg`);card.style.setProperty('--fan-y',`${Math.abs(offset)*4}px`);card.style.zIndex=i+1;$('#hand').appendChild(card)});$('#end-turn').disabled=state.locked}
document.querySelectorAll('.chart-node').forEach(n=>n.onclick=enterNode);document.addEventListener('click',e=>{if(selected&&!e.target.closest('.card')&&!e.target.closest('.enemy-target')&&!e.target.closest('.hero'))cancelTarget()});document.addEventListener('keydown',e=>{if(e.key==='Escape')cancelTarget()});$('.hero').onclick=chooseSelf;$('#start-game').onclick=()=>{audio.start();$('#welcome').classList.add('hidden')};$('#audio-toggle').onclick=()=>audio.toggle();$('#dock-button').onclick=openDrydock;$('#end-turn').onclick=endTurn;$('#restart').onclick=newRun;$('#skip-reward').onclick=()=>overlayClose();globalThis.addEventListener('pagehide',()=>audio.stop(),{once:true});newRun();
