const cards={
  cut:{name:'破浪斩',cost:1,type:'attack',art:'assets/cards/cut.webp',text:'造成 7 点伤害。',damage:7},brace:{name:'压舷',cost:1,type:'skill',art:'assets/cards/brace.webp',text:'获得 6 点护甲。',block:6},
  flare:{name:'信号焰',cost:0,type:'attack',art:'assets/cards/flare.webp',text:'造成 3 点伤害。抽 1 张牌。',damage:3,draw:1},broadside:{name:'舷侧齐射',cost:2,type:'attack',art:'assets/cards/broadside.webp',text:'造成 15 点伤害。',damage:15},
  tidewall:{name:'潮汐壁垒',cost:2,type:'skill',art:'assets/cards/tidewall.webp',text:'获得 14 点护甲。',block:14},mark:{name:'标定航线',cost:1,type:'skill',art:'assets/cards/mark.webp',text:'获得 4 点护甲。抽 2 张牌。',block:4,draw:2},
  undertow:{name:'暗流',cost:1,type:'attack',art:'assets/cards/undertow.webp',text:'造成 5 点伤害。施加 2 层锈蚀。',damage:5,vulnerable:2},salvage:{name:'沉船打捞',cost:1,type:'skill',art:'assets/cards/salvage.webp',text:'获得 8 点护甲。恢复 2 点生命。',block:8,heal:2},
  storm:{name:'风暴眼',cost:3,type:'attack',art:'assets/cards/storm.webp',text:'造成 24 点伤害。',damage:24},current:{name:'顺流',cost:0,type:'skill',art:'assets/cards/current.webp',text:'获得 1 点潮力。抽 1 张牌。',energy:1,draw:1},
  harpoon:{name:'回收鱼叉',cost:1,type:'attack',art:'assets/cards/harpoon.webp',text:'造成 9 点伤害。',damage:9},calm:{name:'静水时刻',cost:1,type:'skill',art:'assets/cards/calm.webp',text:'获得 5 点护甲。恢复 3 点生命。',block:5,heal:3}
};
const encounters=[
  [
    {name:'盐蚀掠夺者',title:'从雾里包抄',sprite:'raider',variant:0,hp:27,moves:[{kind:'attack',value:6},{kind:'blockAttack',value:4,block:4},{kind:'attack',value:8}]},
    {name:'焦油鸥',title:'啄食落单的水手',sprite:'raider',variant:1,hp:21,moves:[{kind:'attack',value:5},{kind:'attack',value:7},{kind:'block',block:6}]}
  ],
  [
    {name:'铆钉潜兽',title:'以沉船的铁骨为食',sprite:'raider',variant:2,hp:44,moves:[{kind:'attack',value:9},{kind:'block',block:10},{kind:'attack',value:13}]},
    {name:'深沟拖网者',title:'把猎物拖入暗流',sprite:'raider',variant:3,hp:32,moves:[{kind:'blockAttack',value:6,block:5},{kind:'attack',value:10},{kind:'attack',value:7}]}
  ],
  [{name:'无灯领航者',title:'它知道每一条错误的航线',sprite:'boss',variant:0,hp:82,moves:[{kind:'attack',value:13},{kind:'blockAttack',value:9,block:8},{kind:'attack',value:18},{kind:'block',block:14}]}]
];
let state,selected=null;
const $=s=>document.querySelector(s);
const audio=createGameAudio();
function createGameAudio(){
  const tracks={map:'assets/audio/map-fog-sea.mp3',battle:'assets/audio/battle-black-sails.mp3',boss:'assets/audio/boss-storm-pursuit.mp3'};
  let context=null,master=null,currentTrack=null,currentScene='map',started=false,muted=false;
  function ensure(){if(context)return context;const AudioContext=globalThis.AudioContext||globalThis.webkitAudioContext;if(!AudioContext)return null;context=new AudioContext();master=context.createGain();master.gain.value=.42;master.connect(context.destination);return context}
  function tone(from,to,duration,type='triangle',volume=.16,delay=0){const ctx=ensure();if(!ctx||muted)return;const now=ctx.currentTime+delay,osc=ctx.createOscillator(),gain=ctx.createGain();osc.type=type;osc.frequency.setValueAtTime(from,now);osc.frequency.exponentialRampToValueAtTime(Math.max(20,to),now+duration);gain.gain.setValueAtTime(.001,now);gain.gain.exponentialRampToValueAtTime(volume,now+.015);gain.gain.exponentialRampToValueAtTime(.001,now+duration);osc.connect(gain).connect(master);osc.start(now);osc.stop(now+duration+.03)}
  function noise(duration=.25,volume=.16,frequency=900){const ctx=ensure();if(!ctx||muted)return;const length=Math.floor(ctx.sampleRate*duration),buffer=ctx.createBuffer(1,length,ctx.sampleRate),data=buffer.getChannelData(0);for(let i=0;i<length;i++)data[i]=(Math.random()*2-1)*(1-i/length);const source=ctx.createBufferSource(),filter=ctx.createBiquadFilter(),gain=ctx.createGain();source.buffer=buffer;filter.type='lowpass';filter.frequency.value=frequency;gain.gain.value=volume;source.connect(filter).connect(gain).connect(master);source.start()}
  function play(name){if(!started||muted)return;ensure()?.resume();if(name==='select'){tone(310,520,.12,'triangle',.1);tone(620,430,.1,'sine',.06,.07)}else if(name==='cannon'){tone(82,38,.38,'sawtooth',.28);noise(.3,.32,520)}else if(name==='hit'){tone(120,54,.22,'square',.16);noise(.18,.2,1200)}else if(name==='shield'){tone(180,760,.48,'sine',.16);tone(260,920,.54,'triangle',.08,.05)}else if(name==='turn'){tone(420,380,.45,'sine',.11);tone(630,560,.4,'sine',.08,.12)}else if(name==='reward'){[440,554,659].forEach((f,i)=>tone(f,f*1.01,.35,'triangle',.09,i*.1))}else if(name==='victory'){[392,494,587,784].forEach((f,i)=>tone(f,f*1.02,.55,'triangle',.12,i*.14))}else if(name==='defeat'){[220,174,130].forEach((f,i)=>tone(f,f*.72,.6,'sawtooth',.1,i*.18))}else if(name==='sail'){noise(.5,.07,340);tone(260,210,.45,'sine',.07)}}
  function setScene(scene){currentScene=scene;if(!started||muted)return;if(currentTrack?.dataset.scene===scene&&!currentTrack.paused)return;currentTrack?.pause();const music=new Audio(tracks[scene]);music.dataset.scene=scene;music.loop=true;music.volume=scene==='map'?.3:.26;currentTrack=music;music.play().catch(()=>{})}
  function start(){started=true;ensure()?.resume();setScene(currentScene);play('sail');updateButton()}
  function toggle(){muted=!muted;if(muted)currentTrack?.pause();else setScene(currentScene);if(master)master.gain.value=muted?0:.42;updateButton();return muted}
  function updateButton(){const button=$('#audio-toggle');if(!button)return;button.textContent=muted?'声音 关':'声音 开';button.setAttribute('aria-pressed',String(muted))}
  function stop(){currentTrack?.pause();context?.close();context=null}
  return{start,toggle,play,setScene,stop}
}
function newRun(){state={floor:0,gold:90,hero:{hp:72,max:72,block:0},enemies:[],deck:['cut','cut','cut','cut','brace','brace','brace','brace','flare','broadside'],draw:[],discard:[],hand:[],energy:3,turn:1,locked:false};$('#overlay').classList.add('hidden');showMap();$('#welcome').classList.remove('hidden')}
function showMap(){cancelTarget();audio.setScene('map');$('#battle-scene').classList.add('hidden');$('#map-scene').classList.remove('hidden');renderHud();renderMap()}
function enterNode(){if(Number(this.dataset.floor)===state.floor){audio.play('sail');startBattle()}}
function startBattle(){audio.setScene(state.floor===encounters.length-1?'boss':'battle');state.enemies=encounters[state.floor].map(e=>({...e,hp:e.hp,max:e.hp,block:0,move:0,vulnerable:0}));state.draw=shuffle([...state.deck]);state.discard=[];state.hand=[];state.turn=1;state.energy=3;state.hero.block=0;state.locked=false;draw(5);$('#map-scene').classList.add('hidden');$('#battle-scene').classList.remove('hidden');render();announce('你的回合')}
function shuffle(a){for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function draw(n){for(let i=0;i<n;i++){if(!state.draw.length){if(!state.discard.length)return;state.draw=shuffle(state.discard);state.discard=[]}if(state.hand.length<8)state.hand.push(state.draw.pop())}}
function play(index,targetIndex=null){
  if(state.locked)return;const id=state.hand[index],c=cards[id];if(!c||c.cost>state.energy)return announce('潮力不足');
  if(c.type==='attack'){const target=state.enemies[targetIndex];if(!target||target.hp<=0)return;audio.play('cannon');const enemyEl=document.querySelector(`.enemy-target[data-index="${targetIndex}"]`);animateAttack($('.hero'),enemyEl,'hero');let amount=c.damage;if(target.vulnerable>0)amount=Math.ceil(amount*1.5);deal(target,amount,enemyEl?.querySelector('.portrait'));if(c.vulnerable)target.vulnerable+=c.vulnerable}
  state.energy-=c.cost;if(c.block){audio.play('shield');state.hero.block+=c.block;showShield($('.hero'))}else if(c.type==='skill')audio.play('select');if(c.heal)state.hero.hp=Math.min(state.hero.max,state.hero.hp+c.heal);if(c.energy)state.energy+=c.energy;state.hand.splice(index,1);state.discard.push(id);if(c.draw)draw(c.draw);cancelTarget();render();if(state.enemies.every(e=>e.hp<=0))winBattle()
}
function deal(target,amount,element){const absorbed=Math.min(target.block,amount),taken=amount-absorbed;target.block-=absorbed;target.hp=Math.max(0,target.hp-taken);if(taken)audio.play('hit');if(element){const unit=element.closest('.combatant')||element;unit.classList.remove('damage-flash');void unit.offsetWidth;unit.classList.add('damage-flash');spawnNumber(element,taken?`-${taken}`:'格挡',taken>0);spawnSparks(element,taken>0)}}
function spawnNumber(el,text,hurt){const r=el.getBoundingClientRect(),n=document.createElement('div');n.className=`float-number ${hurt?'hurt':'blocked'}`;n.textContent=text;n.style.left=`${r.left+r.width/2}px`;n.style.top=`${r.top+r.height/3}px`;document.body.appendChild(n);setTimeout(()=>n.remove(),850)}
function spawnSparks(el,hurt){if(!hurt)return;const r=el.getBoundingClientRect();for(let i=0;i<7;i++){const s=document.createElement('i');s.className='hit-spark';s.style.left=`${r.left+r.width/2}px`;s.style.top=`${r.top+r.height/2}px`;s.style.setProperty('--sx',`${(Math.random()-.5)*100}px`);s.style.setProperty('--sy',`${-20-Math.random()*70}px`);document.body.appendChild(s);setTimeout(()=>s.remove(),620)}}
function showShield(unit){if(!unit)return;const r=unit.getBoundingClientRect(),s=document.createElement('div');s.className='shield-burst';s.style.left=`${r.left+r.width/2}px`;s.style.top=`${r.top+r.height/2}px`;document.body.appendChild(s);unit.classList.add('bracing');setTimeout(()=>unit.classList.remove('bracing'),500);setTimeout(()=>s.remove(),720)}
function animateAttack(source,target,side){if(!source||!target)return;source.classList.add('ship-attacking');const a=source.querySelector('.portrait').getBoundingClientRect(),b=target.querySelector('.portrait').getBoundingClientRect(),shot=document.createElement('div');shot.className=`cannon-shot ${side}`;shot.style.left=`${a.left+a.width/2}px`;shot.style.top=`${a.top+a.height*.58}px`;shot.style.setProperty('--dx',`${b.left+b.width/2-(a.left+a.width/2)}px`);shot.style.setProperty('--dy',`${b.top+b.height*.55-(a.top+a.height*.58)}px`);document.body.appendChild(shot);setTimeout(()=>source.classList.remove('ship-attacking'),420);setTimeout(()=>shot.remove(),520)}
function endTurn(){if(state.locked)return;audio.play('turn');cancelTarget();state.locked=true;state.discard.push(...state.hand);state.hand=[];render();announce('敌方回合');setTimeout(()=>runEnemyTurn(0),650)}
function runEnemyTurn(index){while(index<state.enemies.length&&state.enemies[index].hp<=0)index++;if(index>=state.enemies.length)return setTimeout(beginTurn,550);const enemy=state.enemies[index],m=enemy.moves[enemy.move%enemy.moves.length],enemyEl=document.querySelector(`.enemy-target[data-index="${index}"]`);enemy.block=0;if(m.block){audio.play('shield');enemy.block+=m.block;showShield(enemyEl)}if(m.value){audio.play('cannon');animateAttack(enemyEl,$('.hero'),'enemy');setTimeout(()=>{deal(state.hero,m.value,$('#hero-portrait'));finishEnemyAction(enemy,index)},230)}else finishEnemyAction(enemy,index)}
function finishEnemyAction(enemy,index){enemy.move++;if(enemy.vulnerable>0)enemy.vulnerable--;render();if(state.hero.hp<=0)return gameOver();setTimeout(()=>runEnemyTurn(index+1),520)}
function beginTurn(){state.hero.block=0;state.energy=3;state.turn++;state.locked=false;draw(5);render();announce('你的回合')}
function intentText(enemy){const m=enemy.moves[enemy.move%enemy.moves.length];if(m.kind==='block')return `防御 ${m.block}`;if(m.kind==='blockAttack')return `攻击 ${m.value} · 护甲 ${m.block}`;return `攻击 ${m.value}`}
function announce(text){const b=$('#turn-banner');b.firstChild.textContent=text;b.querySelector('small').textContent=`第 ${state.turn} 回合`;b.classList.remove('show');void b.offsetWidth;b.classList.add('show')}
function selectTargetCard(index,card,event,targetType){event.stopPropagation();if(state.locked||cards[state.hand[index]].cost>state.energy)return announce('潮力不足');if(selected?.index===index)return cancelTarget();audio.play('select');cancelTarget();selected={index,card,targetType,x:event.clientX,y:event.clientY};card.classList.add('selected');const targeting=$('#targeting');targeting.classList.remove('hidden');targeting.classList.toggle('defense',targetType==='hero');if(targetType==='enemy')document.querySelectorAll('.enemy-target:not(.defeated)').forEach(e=>e.classList.add('target-ready'));else $('.hero').classList.add('self-target-ready');window.addEventListener('pointermove',moveTarget);moveTarget(event);$('#hint').textContent=targetType==='enemy'?'移动箭头并点击一名敌人 · Esc 取消':'移动箭头并点击自己的船 · Esc 取消'}
function selectAttack(index,card,event){selectTargetCard(index,card,event,'enemy')}
function selectDefense(index,card,event){selectTargetCard(index,card,event,'hero')}
function moveTarget(event){if(!selected)return;selected.x=event.clientX;selected.y=event.clientY;const r=selected.card.getBoundingClientRect(),sx=r.left+r.width/2,sy=r.top+8,ex=event.clientX,ey=event.clientY,curve=Math.max(55,Math.abs(ex-sx)*.25);$('#target-path').setAttribute('d',`M ${sx} ${sy} C ${sx} ${sy-curve}, ${ex} ${ey+curve}, ${ex} ${ey}`);if(selected.targetType==='enemy')document.querySelectorAll('.enemy-target:not(.defeated)').forEach(enemy=>{const er=enemy.getBoundingClientRect();enemy.classList.toggle('target-hover',ex>=er.left&&ex<=er.right&&ey>=er.top&&ey<=er.bottom)});else{const hero=$('.hero'),hr=hero.getBoundingClientRect();hero.classList.toggle('self-target-hover',ex>=hr.left&&ex<=hr.right&&ey>=hr.top&&ey<=hr.bottom)}}
function chooseTarget(index,event){event.stopPropagation();if(!selected||selected.targetType!=='enemy'||state.enemies[index].hp<=0)return;play(selected.index,index)}
function chooseSelf(event){event.stopPropagation();if(!selected||selected.targetType!=='hero')return;play(selected.index)}
function cancelTarget(){window.removeEventListener('pointermove',moveTarget);selected?.card?.classList.remove('selected');selected=null;$('#targeting').classList.add('hidden');$('#targeting').classList.remove('defense');document.querySelectorAll('.enemy-target').forEach(e=>e.classList.remove('target-ready','target-hover'));$('.hero')?.classList.remove('self-target-ready','self-target-hover');const hint=$('#hint');if(hint)hint.textContent='攻击牌点敌船 · 防御牌点自己的船'}
function winBattle(){state.locked=true;render();setTimeout(()=>state.floor===encounters.length-1?victory():showRewards(),650)}
function showRewards(){audio.play('reward');const pool=Object.keys(cards).filter(x=>!['cut','brace'].includes(x)),picks=shuffle([...pool]).slice(0,3);$('#modal-eyebrow').textContent=`第 ${state.floor+1} 场战斗 · 已完成`;$('#modal-title').textContent='选择一张卡牌';$('#modal-copy').textContent='它将加入你的牌组。随后返回航线图。';$('#rewards').innerHTML='';picks.forEach(id=>$('#rewards').appendChild(cardElement(id,null,true)));$('#skip-reward').classList.remove('hidden');$('#overlay').classList.remove('hidden')}
function takeReward(id){state.deck.push(id);returnToMap()}
function returnToMap(){state.floor++;state.hero.hp=Math.min(state.hero.max,state.hero.hp+12);$('#overlay').classList.add('hidden');showMap()}
function gameOver(){audio.play('defeat');showEnd('航线中断','你的船沉入了无光海。下一次航行会保留你的经验。','再次启航')}
function victory(){audio.play('victory');showEnd('你穿过了风暴','塔心的灯重新亮起。首次远航完成。','开始新航程')}
function showEnd(title,copy,button){$('#modal-eyebrow').textContent='航程记录';$('#modal-title').textContent=title;$('#modal-copy').textContent=copy;$('#rewards').innerHTML=`<button class="primary-button" id="again">${button}</button>`;$('#skip-reward').classList.add('hidden');$('#overlay').classList.remove('hidden');$('#again').onclick=newRun}
function cardElement(id,index,reward=false){const c=cards[id],b=document.createElement('button');b.className=`card ${c.type}${!reward&&c.cost>state.energy?' unplayable':''}`;b.innerHTML=`<span class="card-cost">${c.cost}</span><div class="card-art"><img src="${c.art}" alt=""></div><h3>${c.name}</h3><p>${c.text}</p><span class="card-type">${c.type==='attack'?'攻击':'技能'}</span>`;if(reward)b.onclick=()=>takeReward(id);else if(c.type==='attack')b.onclick=e=>selectAttack(index,b,e);else if(c.block)b.onclick=e=>selectDefense(index,b,e);else b.onclick=e=>{e.stopPropagation();play(index)};return b}
function enemyElement(enemy,index){const el=document.createElement('article'),src=enemy.sprite==='boss'?'assets/boss-ship-v1.png':'assets/raider-ship-v1.png';el.className=`combatant enemy enemy-target ship-${enemy.sprite}${enemy.block?' has-block':''}${enemy.hp<=0?' defeated':''}`;el.dataset.index=index;el.style.setProperty('--variant',enemy.variant||0);el.innerHTML=`<div class="intent"><small>下一步</small><strong>${enemy.hp>0?intentText(enemy):'已击败'}</strong></div><div class="portrait enemy-portrait"><img class="ship-sprite" src="${src}" alt="${enemy.name}"></div><div class="nameplate"><strong>${enemy.name}</strong><small>${enemy.title}</small></div><div class="health"><div style="width:${enemy.hp/enemy.max*100}%"></div><span>${enemy.hp} / ${enemy.max}</span></div><div class="status-row"><span class="status ${enemy.block?'':'hidden'}">护甲 ${enemy.block}</span><span>${enemy.vulnerable?`锈蚀 ${enemy.vulnerable}`:''}</span></div>`;el.onclick=e=>chooseTarget(index,e);return el}
function renderHud(){$('#hud-hp').textContent=`${state.hero.hp} / ${state.hero.max}`;$('#hud-gold').textContent=state.gold;$('#floor').textContent=`${Math.min(state.floor+1,encounters.length)} / ${encounters.length}`;$('#deck-count').textContent=state.deck.length}
function renderMap(){const positions=[[15,77],[51,50],[86,20]],pos=positions[Math.min(state.floor,2)];document.querySelectorAll('.chart-node').forEach((node,i)=>{node.classList.toggle('cleared',i<state.floor);node.classList.toggle('current',i===state.floor);node.classList.toggle('locked',i>state.floor);node.disabled=i!==state.floor});$('#map-ship-token').style.setProperty('--ship-x',`${pos[0]}%`);$('#map-ship-token').style.setProperty('--ship-y',`${pos[1]}%`);$('#map-guidance').textContent=state.floor===2?'风暴中心就在前方。准备迎战首领。':'点击发光节点进入战斗'}
function render(){renderHud();const h=state.hero;$('.hero').classList.toggle('has-block',h.block>0);$('#hero-health').textContent=`${h.hp} / ${h.max}`;$('#hero-health-bar').style.width=`${h.hp/h.max*100}%`;$('#hero-block').textContent=`护甲 ${h.block}`;$('#hero-block').classList.toggle('hidden',!h.block);$('#energy').textContent=state.energy;$('#draw-count').textContent=state.draw.length;$('#discard-count').textContent=state.discard.length;$('#enemies').innerHTML='';state.enemies.forEach((enemy,i)=>$('#enemies').appendChild(enemyElement(enemy,i)));$('#hand').innerHTML='';const mid=(state.hand.length-1)/2;state.hand.forEach((id,i)=>{const card=cardElement(id,i),offset=i-mid;card.style.setProperty('--rot',`${offset*3.5}deg`);card.style.setProperty('--fan-y',`${Math.abs(offset)*4}px`);card.style.zIndex=i+1;$('#hand').appendChild(card)});$('#end-turn').disabled=state.locked}
document.querySelectorAll('.chart-node').forEach(n=>n.onclick=enterNode);document.addEventListener('click',e=>{if(selected&&!e.target.closest('.card')&&!e.target.closest('.enemy-target')&&!e.target.closest('.hero'))cancelTarget()});document.addEventListener('keydown',e=>{if(e.key==='Escape')cancelTarget()});$('.hero').onclick=chooseSelf;$('#start-game').onclick=()=>{audio.start();$('#welcome').classList.add('hidden')};$('#audio-toggle').onclick=()=>audio.toggle();$('#end-turn').onclick=endTurn;$('#restart').onclick=newRun;$('#skip-reward').onclick=returnToMap;globalThis.addEventListener('pagehide',()=>audio.stop(),{once:true});newRun();
